### ISSUE TITLE
[BUG]Decimal places on the GUI

### ISSUE THREAD

**Issue by KirikauKiwi** [DeeEmm/DIY-Flow-Bench#207]
**Software Version**
- RELEASE V.2.0-RC.8
- BUILD_NUMBER Build 24110704

**Describe the bug**
When changing the Flow decimal accuracy from "tenths" to "hundredths" on the web GUI configuration page. After clicking save, the change are made, however all the other displayed numbers are then rounded to their nearest whole number.
When reverting back to "tenths" the other displayed numbers remain as a whole number.

The General Decimal accuracy drop down has disappeared from the GUI.

**Expected behavior**
When changing the Flow accuracy that the other displayed numbers are not changed

**Missing General Decimal Accuracy Dropdown**
<img width="662" alt="Screenshot 2024-11-08 at 02 24 12" src="https://github.com/user-attachments/assets/e707fb2e-9be8-4870-a5f0-10425d6599ce">

**Flow Accuracy set to Hundredths**
<img width="743" alt="Screenshot 2024-11-08 at 02 24 22" src="https://github.com/user-attachments/assets/6d9110c8-a27f-4606-acce-898fc59cf0a4">

**Comment by DeeEmm** [comment]
Hmnnn something strange happening here. I note that the drop down is missing in the GUI. 

Likely related. Suspect an issue in the javascript. Will take a look.

Most likely a search and destroy victim

<img width="733" alt="Screenshot 2024-11-08 at 7 27 16 pm" src="https://github.com/user-attachments/assets/7ea1c499-39d7-4e37-8ac4-b17069125779">

**Comment by DeeEmm** [comment]
Was two issues.

- Missing JSON statements preventing decimal places from being saved to config file.
- Missing ' from HTML code for dropdown, preventing value from being sent in POST. (always sent zero)

Test the updated code and let me know if it works for you

**Comment by KirikauKiwi** [comment]
Yes all working for the decimals points 👍 

One other thing I just noticed is when on the Dashboard page of the GUI and I click refresh in Safari it takes me to the Configuration page, is this the expected behaviour? or should it refresh to the page you were viewing?

**Comment by DeeEmm** [comment]
Depending on where you have been you might find that the URL in the address bar is set to /?view=config. This is intentional and is usually a result of the the redirect created when you save data whilst viewing the configuration tab.

In these cases when you save the configuration, it redirects you back to the configuration tab after the page refreshes,  which is the default behaviour.

If you then navigate to another tab the URL is not changed, as it does not 'navigate', but instead changes the display using javascript. So if at some point you refresh the page it will send you to the 'config' tab.

We can negate this behaviour by always redirecting to the main page after saving data.

**Comment by KirikauKiwi** [comment]
I think that would be a useful small change as I would think in most cases that after saving a change you would want to go to the main page.

**Comment by DeeEmm** [comment]
An easy fix. Consider it done.

As this issue is fixed, I'll close this out.
